In [ ]:
import pandas as pd
datos = {
    "experiencia": [1, 2, 3, 5, 7, 10, 4, 6, 8, 2, 9, 3],
    "lenguaje": [
        "python", "java", "csharp", "python",
        "java", "csharp", "java", "python",
        "csharp", "python", "java", "csharp"
    ],
    "rango": [
        "junior", "junior", "intermedio", "intermedio",
        "senior", "senior", "intermedio", "senior",
        "senior", "junior", "senior", "intermedio"
    ],
    "pret_salarial": [
        1500, 1800, 2500, 3000,
        4500, 5000, 2800, 4200,
        4800, 1700, 5500, 2700
    ],
    "contratado": [
        "si", "no", "si", "si",
        "si", "si", "no", "si",
        "si", "no", "si", "no"
    ]
}
df = pd.DataFrame(datos)
print(df)

    experiencia lenguaje       rango  pret_salarial contratado
0             1   python      junior           1500         si
1             2     java      junior           1800         no
2             3   csharp  intermedio           2500         si
3             5   python  intermedio           3000         si
4             7     java      senior           4500         si
5            10   csharp      senior           5000         si
6             4     java  intermedio           2800         no
7             6   python      senior           4200         si
8             8   csharp      senior           4800         si
9             2   python      junior           1700         no
10            9     java      senior           5500         si
11            3   csharp  intermedio           2700         no

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder, LabelBinarizer

In [ ]:
x_num= df[['experiencia','pret_salarial']]
x_num

    experiencia  pret_salarial
0             1           1500
1             2           1800
2             3           2500
3             5           3000
4             7           4500
5            10           5000
6             4           2800
7             6           4200
8             8           4800
9             2           1700
10            9           5500
11            3           2700

In [ ]:
x_nominal= df[['lenguaje']]
x_nominal

   lenguaje
0    python
1      java
2    csharp
3    python
4      java
5    csharp
6      java
7    python
8    csharp
9    python
10     java
11   csharp

In [ ]:
x_ordinal= df[['rango']]
x_ordinal

         rango
0       junior
1       junior
2   intermedio
3   intermedio
4       senior
5       senior
6   intermedio
7       senior
8       senior
9       junior
10      senior
11  intermedio

In [ ]:
num_scaler= StandardScaler()
nominal_encoder= OneHotEncoder(sparse_output=False)
ordinal_encoder= LabelEncoder()

In [ ]:
x_num_scaled= num_scaler.fit_transform(x_num)
x_num_scaled

array([[-1.39970842, -1.36627516],
       [-1.04978132, -1.14270286],
       [-0.69985421, -0.62103416],
       [ 0.        , -0.24841367],
       [ 0.69985421,  0.86944783],
       [ 1.74963553,  1.24206833],
       [-0.34992711, -0.39746186],
       [ 0.34992711,  0.64587553],
       [ 1.04978132,  1.09302013],
       [-1.04978132, -1.21722696],
       [ 1.39970842,  1.61468882],
       [-0.69985421, -0.47198596]])

In [ ]:
x_nominal_encoded= nominal_encoder.fit_transform(x_nominal)
x_nominal_encoded

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
x_ordinal_encoded= ordinal_encoder.fit_transform(x_ordinal)
x_ordinal_encoded

/usr/local/lib/python3.13/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([1, 1, 0, 0, 2, 2, 0, 2, 2, 1, 2, 0])

In [ ]:
y_cat= df[['contratado']]
y_cat

   contratado
0          si
1          no
2          si
3          si
4          si
5          si
6          no
7          si
8          si
9          no
10         si
11         no

In [ ]:
label_binarizer= LabelBinarizer() #BINARIZAR ETIQUETAS (Y)
y_cat_binarized= label_binarizer.fit_transform(y_cat)
y_cat_binarized

array([[1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0]])

In [ ]:
#unimos todo
import numpy as np

In [ ]:
np.hstack([x_num_scaled, x_nominal_encoded, x_ordinal_encoded.reshape(-1,1), y_cat_binarized])

array([[-1.39970842, -1.36627516,  0.        ,  0.        ,  1.        ,
         1.        ,  1.        ],
       [-1.04978132, -1.14270286,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.69985421, -0.62103416,  1.        ,  0.        ,  0.        ,
         0.        ,  1.        ],
       [ 0.        , -0.24841367,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.69985421,  0.86944783,  0.        ,  1.        ,  0.        ,
         2.        ,  1.        ],
       [ 1.74963553,  1.24206833,  1.        ,  0.        ,  0.        ,
         2.        ,  1.        ],
       [-0.34992711, -0.39746186,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.34992711,  0.64587553,  0.        ,  0.        ,  1.        ,
         2.        ,  1.        ],
       [ 1.04978132,  1.09302013,  1.        ,  0.        ,  0.        ,
         2.        ,  1.        ],
       [-1.04978132, -1.21722696,  0.        ,  0.        ,  1.        ,
         1.        ,  0.        ],
       [ 1.39970842,  1.61468882,  0.        ,  1.        ,  0.        ,
         2.        ,  1.        ],
       [-0.69985421, -0.47198596,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])